### ISSUE TITLE
Question: Where is FSharp wrapper?

### ISSUE THREAD

**Issue by dburriss** [louthy/echo-process#30]
In the docs there is a reference to an `Echo.Process.FSharp` but I can't find any other references or packages.

Doing something like this at the moment but not sure what types of trouble I am getting myself into.

```fsharp
let init = Echo.ProcessConfig.initialise()

let inline spawn<'a> (name:string) (f:'a -> unit) (terminated:(ProcessId -> unit) option) = 
    let flags = ProcessFlags.Default
    let strategy = Strategy.OneForOne(Strategy.Always(Directive.Restart))
    let mailboxSize = -1
    let t = Action<ProcessId>(defaultArg terminated (fun _ -> ()))
    let action = Action<'a> f
    Process.spawn<'a>(ProcessName(name), action, flags, strategy, mailboxSize, t)

let publish msg = Process.publish msg |> FSharp.fs

let tell<'a> (pid:ProcessId) (msg:'a) (sender: ProcessId option) =
    let s = defaultArg sender ProcessId.None
    Process.tell<'a>(pid, msg, s)

let tellAt<'a> (pid:ProcessId) (msg:'a) (dt:DateTime) (sender: ProcessId option) =
    let s = defaultArg sender ProcessId.None
    Process.tell<'a>(pid, msg, dt, s)

let tellLater<'a> (pid:ProcessId) (msg:'a) (t:TimeSpan) (sender: ProcessId option) =
    let s = defaultArg sender ProcessId.None
    Process.tell<'a>(pid, msg, t, s)
```

**Comment by louthy** [comment]
@dburriss Hi Devon, I dropped support because I got so fed up of trying to get the FS projects working with NETCore.  It became impossible to support so I killed it.

These are some gists of the original source.  You could build yourself a project from these files and it will give you most of what you'll need.  Note, they're potentially a little out of date, so just be aware you may need to fix up some compilation issues:

* [Prelude.fs](https://gist.github.com/louthy/4dfe2268c657dbf53a166a8a165e6b11)
* [Role.fs](https://gist.github.com/louthy/8a384ed1bae3c640ac46798d3533d464)
* [Dispatch.fs](https://gist.github.com/louthy/a029882a30a1c6eb96483f8acd79efa0)
* [Router.fs](https://gist.github.com/louthy/5597607cc5ec603d836544e6ebeadc2d)

**Comment by dburriss** [comment]
@louthy thanks for the reply. Yes I can understand the frustration with NETCore as a whole and F# in particular.

I will check those out if I need them. I jumped over to C# to learn the library a bit but couldn't figure out in an expedient amount of time if creating a single computational unit across multiple machines was possible.
