### ISSUE TITLE
null reference error when disposing system

### ISSUE THREAD

**Issue by StefanBertels** [louthy/echo-process#43]
There is a bug in shutdown. I could not build a small example reproducing this yet, but I could find the bug:

In https://github.com/louthy/echo-process/blob/master/Echo.Process/ActorSys/ActorSystem.cs#L173 the `rootItem` is set to `null` but it is used later via https://github.com/louthy/echo-process/blob/master/Echo.Process/ActorSys/ActorSystem.cs#L196 which calls https://github.com/louthy/echo-process/blob/master/Echo.Process/ActorSys/ActorSystem.cs#L789 and there `rootItem` will be passed to handle children shutdown.

I had a situation where this resulted somehow in a dead lock (but could not find out why) when I called shutdownAll during actor setup.

**Comment by louthy** [comment]
I have added a speculative fix for this (because obviously there's no repro-step here, so it's hard to know for sure).  But the fix maintains `rootItem` until the end of the shutdown process and uses another flag to indicate the system is shutting down.  If you want to give it a try and feedback, that'd be cool.
