### ISSUE TITLE
Current performance state compared to Akka.NET and Orleans

### ISSUE THREAD

**Issue by Kavignon** [louthy/echo-process#64]
Hi @louthy,

This project looks really great! Kudos for this great idea for actor model with an FP API! I might be faced with a development story where I could leverage the actor model to see the performance gains in my system. As of now, I see Akka.NET and Microsoft's Orleans are the two main things for concurrency on the MSFT stack but I'd like to know, what's the current state of echo-process?

I've already included LanguageExt.Core in our toolchain and this could be a smooth add-on to the system if the performance does the job from the echo side of things!

**Comment by louthy** [comment]
> what's the current state of echo-process

The documentation is a little light and there may be some roughness in the areas we don't use a lot, but mostly, but it's relatively mature in that it's in been in heavy use in my company for many years now.  I have purposefully kept a relatively low profile with this project (compared to language-ext) because I am very short of time, so having two major OS projects to tend to would be a bit painful right now.  Even with that me (and my team) are doing updates semi-regularly (the recent updates to improve the session system is an example of that).

In terms of performance, I haven't done any major benchmarking outside of little test apps to make sure throughput was decent.  So far we haven't hit any major bottlenecks from that point-of-view.  Akka is likely going to be faster than echo because echo does more work to ensure correctness (type checking of messages before being sent to the target) whereas Akka just accepts anything and relies on dead-letter queues instead.  

The future for echo is to take a more principled approach to describing the network topology and the interaction that Processes support (essentially a type-system for the network), which is something Akka will never do.  So, I guess it depends what your use case is: if you need absolute performance then Akka, if you want a system that gives better handling of incorrectness: echo.

Orleans I didn't rate at all when I saw it.  It looked like an absolute OO nightmare.  But YMMV.
